export const accounts: Account[] = [
  {
    id: "123",
    name: "Carteira",
    entries: [
      {
        id: "123456789",
        type: "EXPENSE",
        description: "Arroz",
        value: 123,
        createdAt: new Date(),
        accountId: "123",
        paid: true,
      },
      {
        id: "123456789",
        type: "EXPENSE",
        description: "Arroz",
        value: 123,
        createdAt: new Date(),
        accountId: "123",
        paid: true,
      },
      {
        id: "123456789",
        type: "INCOME",
        description: "Salário",
        value: 4200,
        createdAt: new Date(),
        accountId: "123",
        paid: true,
      },
      {
        id: "123456789",
        type: "EXPENSE",
        description: "Arroz",
        value: 123,
        createdAt: new Date(),
        accountId: "123",
        paid: true,
      },
      {
        id: "123456789",
        type: "EXPENSE",
        description: "Arroz",
        value: 123,
        createdAt: new Date(),
        accountId: "123",
        paid: true,
      },
    ],
    createdAt: new Date(),
  },
]
